name: Codespell

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    branches:
      - 'master'

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: codespell
        uses: codespell-project/actions-codespell@master
        with:
          skip: .git,*.png,*.jpg,*.svg,*.sum,*.json,*.lock,*.txt,*.test,*.html
          ignore_words_list: aks,keyserver,atleast,dne,ser,ist,isnt,files',ba,dum,iam,te,parm,bumb,nd,sie,thi,GIR
          check_filenames: true
          check_hidden: true
